import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  userSidebar: [{ type: "autogenerated", dirName: "user" }],
  adminSidebar: [{ type: "autogenerated", dirName: "admin" }],
};

export default sidebars;
