name: knights_apparel
services:
  traefik:
    image: traefik:3.5
    pull_policy: 'always'
    restart: 'unless-stopped'
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kassistant:
    image: 'ghcr.io/untw-vnd/ka-kassistant:latest'
    pull_policy: 'always'
    restart: 'unless-stopped'
    ports:
      - "8000:8000"
    env_file:
      - 'kassistant.env'
    depends_on:
      postgres17:
        condition: service_healthy
    labels:
      - "traefik.http.routers.kassistant.rule=Host(`kassistant.docker.localhost`)"

  postgres17:
    image: postgres:17
    pull_policy: 'always'
    restart: 'unless-stopped'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shadow
      POSTGRES_DB: kassistant
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
